#![forbid(unsafe_code)]

use super::generator::derive_target_name;
use super::test_generator::generate_sample_arguments;
use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;

/// Generates idiomatic performance micro-benchmark files for the newly extracted helper function.
pub fn generate_benchmark_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    params: &[InferredParameter],
    language: &str,
) -> Vec<ExtractedFile> {
    let mut bench_files = Vec::new();
    let norm_target = target_path.replace('\\', "/");
    let norm_ext = language.to_lowercase();
    let target_name = derive_target_name(&norm_target);
    let pascal_target = crate::ast::type_infer::to_pascal_case(&target_name);
    let pascal_fn = crate::ast::type_infer::to_pascal_case(function_name);
    let snake_fn = crate::ast::type_infer::to_snake_case(function_name);
    let sample_args = generate_sample_arguments(params);
    let args_joined = sample_args.join(", ");

    match norm_ext.as_str() {
        "rs" => {
            let (file_path, content) = if target_kind == ExtractTargetKind::NewCrate {
                let p = format!(
                    "{}/benches/{}_bench.rs",
                    norm_target.trim_end_matches('/'),
                    snake_fn
                );
                let c = format!(
                    "//! Criterion micro-benchmarks for `{}` generated by CDDM.\n\nuse criterion::{{black_box, criterion_group, criterion_main, Criterion}};\nuse {}::{};\n\nfn bench_{}_throughput(c: &mut Criterion) {{\n    c.bench_function(\"{}\", |b| {{\n        b.iter(|| {{\n            {}({})\n        }});\n    }});\n}}\n\ncriterion_group!(benches, bench_{}_throughput);\ncriterion_main!(benches);\n",
                    function_name, target_name, function_name, snake_fn, function_name, function_name, args_joined, snake_fn
                );
                (p, c)
            } else {
                let p = if norm_target.ends_with(".rs") {
                    norm_target.replace(".rs", "_bench.rs")
                } else {
                    format!("{}_bench.rs", norm_target)
                };
                let c = format!(
                        "//! Performance benchmark for `{}` generated by \
                         CDDM.\n\n#[cfg(test)]\nmod benches {{\n    use super::*;\n    use \
                         std::time::Instant;\n\n    #[test]\n    fn bench_{}_latency() {{\n        \
                         let start = Instant::now();\n        for _ in 0..10_000 {{\n            \
                         std::hint::black_box({}({}));\n        }}\n        let duration = \
                         start.elapsed();\n        println!(\"Executed 10,000 iterations in \
                         {{:?}}\", duration);\n    }}\n}}\n",
                        function_name, snake_fn, function_name, args_joined
                    );
                (p, c)
            };
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "ts" | "tsx" | "js" | "jsx" => {
            let (file_path, import_stmt) = super::generator::resolve_auxiliary_file_path(
                &norm_target,
                &snake_fn,
                function_name,
                "ts",
                target_kind,
                "bench",
            );

            let content = format!(
                "import {{ Bench }} from \"tinybench\";\n{}\n\nconst bench = new Bench({{ time: \
                 100 }});\n\nbench.add(\"{}\", () => {{\n  {}({});\n}});\n\nawait \
                 bench.warmup();\nawait bench.run();\nconsole.table(bench.table());\n",
                import_stmt, function_name, function_name, args_joined
            );
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "py" => {
            let (file_path, import_path) = super::generator::resolve_auxiliary_file_path(
                &norm_target,
                &snake_fn,
                function_name,
                "py",
                target_kind,
                "bench",
            );

            let content = format!(
                "\"\"\"Micro-benchmark for {} generated by CDDM.\"\"\"\n\nimport timeit\n{}\n\n\ndef benchmark_{}_execution(benchmark=None):\n    \"\"\"Benchmark execution throughput.\"\"\"\n    if benchmark:\n        benchmark({})\n    else:\n        timer = timeit.Timer(lambda: {}({}))\n        iters = 10_000\n        elapsed = timer.timeit(number=iters)\n        print(f\"{}: {{elapsed:.6f}}s for {{iters}} iterations\")\n",
                function_name, import_path, snake_fn, function_name, function_name, args_joined, function_name
            );
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "go" => {
            let pkg_name = target_name.replace('-', "_");
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "{}/{}_bench_test.go",
                    norm_target.trim_end_matches('/'),
                    snake_fn
                )
            } else {
                let base = if norm_target.ends_with(".go") {
                    norm_target.trim_end_matches(".go").to_string()
                } else {
                    norm_target.clone()
                };
                format!("{}_bench_test.go", base)
            };

            let content = format!(
                "package {}\n\nimport \"testing\"\n\nfunc Benchmark{}(b *testing.B) \
                 {{\n\tb.ResetTimer()\n\tfor i := 0; i < b.N; i++ {{\n\t\t{}({})\n\t}}\n}}\n",
                pkg_name, pascal_fn, pascal_fn, args_joined
            );
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "java" => {
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "{}/src/test/java/com/cddm/shared/{}UtilsBenchmark.java",
                    norm_target.trim_end_matches('/'),
                    pascal_target
                )
            } else {
                format!("{}/{}UtilsBenchmark.java", norm_target, pascal_target)
            };

            let content = format!(
                "package com.cddm.shared;\n\nimport org.openjdk.jmh.annotations.*;\nimport \
                 java.util.concurrent.TimeUnit;\n\n@BenchmarkMode(Mode.Throughput)\n@\
                 OutputTimeUnit(TimeUnit.MILLISECONDS)\n@State(Scope.Benchmark)\npublic class \
                 {}UtilsBenchmark {{\n    @Benchmark\n    public void bench{}() {{\n        \
                 {}Utils.{}({});\n    }}\n}}\n",
                pascal_target, pascal_fn, pascal_target, function_name, args_joined
            );
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "cs" => {
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "{}/benches/{}UtilsBenchmarks.cs",
                    norm_target.trim_end_matches('/'),
                    pascal_target
                )
            } else {
                format!("{}/{}UtilsBenchmarks.cs", norm_target, pascal_target)
            };

            let content = format!(
                "using BenchmarkDotNet.Attributes;\nusing {};\n\nnamespace {}.Benchmarks\n{{\n    \
                 [MemoryDiagnoser]\n    public class {}UtilsBenchmarks\n    {{\n        \
                 [Benchmark]\n        public void Benchmark{}()\n        {{\n            \
                 {}Utils.{}({});\n        }}\n    }}\n}}\n",
                pascal_target,
                pascal_target,
                pascal_target,
                pascal_fn,
                pascal_target,
                pascal_fn,
                args_joined
            );
            bench_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        _ => {
            let p = format!("{}_bench.{}", norm_target, norm_ext);
            let c = format!(
                "// Automated micro-benchmark generated by CDDM for {}\n{}({});\n",
                function_name, function_name, args_joined
            );
            bench_files.push(ExtractedFile {
                file_path: p,
                content: c,
                is_new: true,
            });
        }
    }

    bench_files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_rust_criterion_benchmarks() {
        let params = vec![InferredParameter {
            name: "val".to_string(),
            inferred_type: "i32".to_string(),
            original_values: vec!["100".to_string()],
        }];
        let files = generate_benchmark_files(
            "crates/math_utils",
            ExtractTargetKind::NewCrate,
            "calculate_sum",
            &params,
            "rs",
        );
        assert_eq!(files.len(), 1);
        assert!(files[0].file_path.contains("calculate_sum_bench.rs"));
        assert!(files[0].content.contains("c.bench_function"));
    }

    #[test]
    fn test_generate_ts_benchmarks() {
        let params = vec![];
        let files = generate_benchmark_files(
            "src/utils/format.ts",
            ExtractTargetKind::NewModule,
            "formatDate",
            &params,
            "ts",
        );
        assert_eq!(files.len(), 1);
        assert!(files[0].file_path.ends_with(".bench.ts"));
        assert!(files[0].content.contains("tinybench"));
    }
}
