#![forbid(unsafe_code)]

use super::generator::AuxiliaryGenContext;
use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;

/// Generates idiomatic performance micro-benchmark files for the newly extracted helper function.
pub fn generate_benchmark_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    params: &[InferredParameter],
    language: &str,
) -> Vec<ExtractedFile> {
    let ctx = AuxiliaryGenContext::new(target_path, function_name, params, language);
    let mut bench_files = Vec::new();

    match ctx.norm_ext.as_str() {
        "rs" => {
            let file_path = ctx.resolve_rs_path(target_kind, "benches", "bench");
            let content = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "//! Criterion micro-benchmarks for `{}` generated by CDDM.\n\nuse criterion::{{black_box, criterion_group, criterion_main, Criterion}};\nuse {}::{};\n\nfn bench_{}_throughput(c: &mut Criterion) {{\n    c.bench_function(\"{}\", |b| {{\n        b.iter(|| {{\n            {}({})\n        }});\n    }});\n}}\n\ncriterion_group!(benches, bench_{}_throughput);\ncriterion_main!(benches);\n",
                    function_name,
                    ctx.target_name,
                    function_name,
                    ctx.snake_fn,
                    function_name,
                    function_name,
                    ctx.args_joined,
                    ctx.snake_fn
                )
            } else {
                format!(
                    "//! Performance benchmark for `{}` generated by CDDM.\n\n#[cfg(test)]\nmod benches {{\n    use super::*;\n    use std::time::Instant;\n\n    #[test]\n    fn bench_{}_latency() {{\n        let start = Instant::now();\n        for _ in 0..10_000 {{\n            std::hint::black_box({}({}));\n        }}\n        let duration = start.elapsed();\n        println!(\"Executed 10,000 iterations in {{:?}}\", duration);\n    }}\n}}\n",
                    function_name, ctx.snake_fn, function_name, ctx.args_joined
                )
            };
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        "ts" | "tsx" | "js" | "jsx" => {
            let (file_path, import_stmt) = super::generator::resolve_auxiliary_file_path(
                &ctx.norm_target,
                &ctx.snake_fn,
                function_name,
                "ts",
                target_kind,
                "bench",
            );

            let content = format!(
                "import {{ Bench }} from \"tinybench\";\n{}\n\nconst bench = new Bench({{ time: \
                 100 }});\n\nbench.add(\"{}\", () => {{\n  {}({});\n}});\n\nawait \
                 bench.warmup();\nawait bench.run();\nconsole.table(bench.table());\n",
                import_stmt, function_name, function_name, ctx.args_joined
            );
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        "py" => {
            let (file_path, import_path) = super::generator::resolve_auxiliary_file_path(
                &ctx.norm_target,
                &ctx.snake_fn,
                function_name,
                "py",
                target_kind,
                "bench",
            );

            let content = format!(
                "\"\"\"Micro-benchmark for {} generated by CDDM.\"\"\"\n\nimport timeit\n{}\n\n\ndef benchmark_{}_execution(benchmark=None):\n    \"\"\"Benchmark execution throughput.\"\"\"\n    if benchmark:\n        benchmark({})\n    else:\n        timer = timeit.Timer(lambda: {}({}))\n        iters = 10_000\n        elapsed = timer.timeit(number=iters)\n        print(f\"{}: {{elapsed:.6f}}s for {{iters}} iterations\")\n",
                function_name,
                import_path,
                ctx.snake_fn,
                function_name,
                function_name,
                ctx.args_joined,
                function_name
            );
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        "go" => {
            let (file_path, pkg_name) = ctx.resolve_go_path(target_kind, "bench");
            let content = format!(
                "package {}\n\nimport \"testing\"\n\nfunc Benchmark{}(b *testing.B) \
                 {{\n\tb.ResetTimer()\n\tfor i := 0; i < b.N; i++ {{\n\t\t{}({})\n\t}}\n}}\n",
                pkg_name, ctx.pascal_fn, ctx.pascal_fn, ctx.args_joined
            );
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        "java" => {
            let file_path = ctx.resolve_jvm_path(target_kind, "UtilsBenchmark");
            let content = format!(
                "package com.cddm.shared;\n\nimport org.openjdk.jmh.annotations.*;\nimport \
                 java.util.concurrent.TimeUnit;\n\n@BenchmarkMode(Mode.Throughput)\n@\
                 OutputTimeUnit(TimeUnit.MILLISECONDS)\n@State(Scope.Benchmark)\npublic class \
                 {}UtilsBenchmark {{\n    @Benchmark\n    public void bench{}() {{\n        \
                 {}Utils.{}({});\n    }}\n}}\n",
                ctx.pascal_target, ctx.pascal_fn, ctx.pascal_target, function_name, ctx.args_joined
            );
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        "cs" => {
            let file_path = ctx.resolve_dotnet_path(target_kind, "Benchmarks");
            let content = format!(
                "using BenchmarkDotNet.Attributes;\nusing {};\n\nnamespace {}.Benchmarks\n{{\n    \
                 [MemoryDiagnoser]\n    public class {}UtilsBenchmarks\n    {{\n        \
                 [Benchmark]\n        public void Benchmark{}()\n        {{\n            \
                 {}Utils.{}({});\n        }}\n    }}\n}}\n",
                ctx.pascal_target,
                ctx.pascal_target,
                ctx.pascal_target,
                ctx.pascal_fn,
                ctx.pascal_target,
                ctx.pascal_fn,
                ctx.args_joined
            );
            bench_files.push(ExtractedFile::new(file_path, content));
        }
        _ => {
            let p = format!("{}_bench.{}", ctx.norm_target, ctx.norm_ext);
            let c = format!(
                "// Automated micro-benchmark generated by CDDM for {}\n{}({});\n",
                function_name, function_name, ctx.args_joined
            );
            bench_files.push(ExtractedFile::new(p, c));
        }
    }

    bench_files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_rust_criterion_benchmarks() {
        let params = vec![InferredParameter {
            name: "val".to_string(),
            inferred_type: "i32".to_string(),
            original_values: vec!["100".to_string()],
        }];
        let files = generate_benchmark_files(
            "crates/math_utils",
            ExtractTargetKind::NewCrate,
            "calculate_sum",
            &params,
            "rs",
        );
        assert_eq!(files.len(), 1);
        assert!(files[0].file_path.contains("calculate_sum_bench.rs"));
        assert!(files[0].content.contains("c.bench_function"));
    }

    #[test]
    fn test_generate_ts_benchmarks() {
        let params = vec![];
        let files = generate_benchmark_files(
            "src/utils/format.ts",
            ExtractTargetKind::NewModule,
            "formatDate",
            &params,
            "ts",
        );
        assert_eq!(files.len(), 1);
        assert!(files[0].file_path.ends_with(".bench.ts"));
        assert!(files[0].content.contains("tinybench"));
    }
}
