#![forbid(unsafe_code)]

use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;
use std::path::Path;

fn wrap_indented_body(code: &str) -> String {
    code.lines()
        .map(|l| {
            if l.is_empty() {
                l.to_string()
            } else {
                format!("    {}", l)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Generates files for the extracted crate or module based on target kind and language.
pub fn generate_extracted_target_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    inferred_params: &[InferredParameter],
    common_body_lines: &[String],
    ext: &str,
) -> (String, Vec<ExtractedFile>) {
    let norm_ext = ext.to_lowercase();
    let norm_target = target_path.replace('\\', "/");
    let target_name = derive_target_name(&norm_target);
    let pascal_target = crate::ast::type_infer::to_pascal_case(&target_name);

    let helper_sig = crate::ast::type_infer::format_function_signature(
        &norm_ext,
        function_name,
        inferred_params,
    );

    let helper_fn = crate::ast::rewriter::synthesize_helper_function_block(
        &norm_ext,
        function_name,
        inferred_params,
        common_body_lines,
        "",
    );

    let mut files = Vec::new();

    match target_kind {
        ExtractTargetKind::NewCrate => match norm_ext.as_str() {
            "rs" => {
                let crate_ident = target_name.replace('-', "_");
                let cargo_toml = format!(
                    "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \
                     \"2021\"\ndescription = \"Extracted shared utility crate generated by \
                     CDDM\"\n\n[dependencies]\n",
                    crate_ident
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/Cargo.toml", norm_target.trim_end_matches('/')),
                    content: cargo_toml,
                    is_new: true,
                });

                let lib_rs = format!(
                    "#![forbid(unsafe_code)]\n\n/// Extracted shared helper generated by \
                     CDDM.\n{}\n",
                    helper_fn.trim()
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/src/lib.rs", norm_target.trim_end_matches('/')),
                    content: lib_rs,
                    is_new: true,
                });
            }
            "ts" | "tsx" | "js" | "jsx" => {
                let pkg_json = format!(
                    "{{\n  \"name\": \"{}\",\n  \"version\": \"0.1.0\",\n  \"description\": \
                     \"Extracted shared package generated by CDDM\",\n  \"main\": \
                     \"./src/index.ts\",\n  \"types\": \"./src/index.ts\"\n}}\n",
                    target_name
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/package.json", norm_target.trim_end_matches('/')),
                    content: pkg_json,
                    is_new: true,
                });

                let index_ts = format!(
                    "/**\n * Extracted shared utilities generated by CDDM.\n */\n\n{}\n",
                    helper_fn.trim()
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/src/index.ts", norm_target.trim_end_matches('/')),
                    content: index_ts,
                    is_new: true,
                });
            }
            "py" => {
                let pyproject = format!(
                    "[project]\nname = \"{}\"\nversion = \"0.1.0\"\ndescription = \"Extracted \
                     shared package generated by CDDM\"\n\n[build-system]\nrequires = \
                     [\"setuptools\"]\nbuild-backend = \"setuptools.build_meta\"\n",
                    target_name
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/pyproject.toml", norm_target.trim_end_matches('/')),
                    content: pyproject,
                    is_new: true,
                });

                let init_py = format!(
                    "\"\"\"Extracted shared package generated by CDDM.\"\"\"\n\n{}\n",
                    helper_fn.trim()
                );
                files.push(ExtractedFile {
                    file_path: format!("{}/__init__.py", norm_target.trim_end_matches('/')),
                    content: init_py,
                    is_new: true,
                });
            }
            "go" => {
                let pkg_name = target_name.replace('-', "_");
                let go_mod = format!("module {}\n\ngo 1.23.0\n", pkg_name);
                files.push(ExtractedFile {
                    file_path: format!("{}/go.mod", norm_target.trim_end_matches('/')),
                    content: go_mod,
                    is_new: true,
                });

                let go_file = format!(
                    "package {}\n\n// Extracted shared utility generated by CDDM.\n{}\n",
                    pkg_name,
                    helper_fn.trim()
                );
                files.push(ExtractedFile {
                    file_path: format!(
                        "{}/{}.go",
                        norm_target.trim_end_matches('/'),
                        function_name.to_lowercase()
                    ),
                    content: go_file,
                    is_new: true,
                });
            }
            "java" => {
                let pom_xml = format!(
                        "<project xmlns=\"http://maven.apache.org/POM/4.0.0\">\n    \
                         <modelVersion>4.0.0</modelVersion>\n    \
                         <groupId>com.cddm.shared</groupId>\n    <artifactId>{}</artifactId>\n    \
                         <version>0.1.0</version>\n</project>\n",
                        target_name.to_lowercase()
                    );
                files.push(ExtractedFile {
                    file_path: format!("{}/pom.xml", norm_target.trim_end_matches('/')),
                    content: pom_xml,
                    is_new: true,
                });

                let indented = wrap_indented_body(&helper_fn);
                let java_class = format!(
                    "package com.cddm.shared;\n\n/**\n * Extracted shared utility generated by \
                     CDDM.\n */\npublic final class {}Utils {{\n    private {}Utils() \
                     {{}}\n\n{}\n}}\n",
                    pascal_target, pascal_target, indented
                );
                files.push(ExtractedFile {
                    file_path: format!(
                        "{}/src/main/java/com/cddm/shared/{}Utils.java",
                        norm_target.trim_end_matches('/'),
                        pascal_target
                    ),
                    content: java_class,
                    is_new: true,
                });
            }
            "cs" => {
                let csproj = "<Project Sdk=\"Microsoft.NET.Sdk\">\n  <PropertyGroup>\n    \
                              <TargetFramework>net8.0</TargetFramework>\n    \
                              <Nullable>enable</Nullable>\n  </PropertyGroup>\n</Project>\n"
                    .to_string();
                files.push(ExtractedFile {
                    file_path: format!(
                        "{}/{}.csproj",
                        norm_target.trim_end_matches('/'),
                        target_name
                    ),
                    content: csproj,
                    is_new: true,
                });

                let indented = wrap_indented_body(&helper_fn);
                let cs_class = format!(
                    "namespace {};\n\n/// <summary>\n/// Extracted shared utility generated by \
                     CDDM.\n/// </summary>\npublic static class {}Utils\n{{\n{}\n}}\n",
                    pascal_target, pascal_target, indented
                );
                files.push(ExtractedFile {
                    file_path: format!(
                        "{}/{}Utils.cs",
                        norm_target.trim_end_matches('/'),
                        pascal_target
                    ),
                    content: cs_class,
                    is_new: true,
                });
            }
            _ => {
                files.push(ExtractedFile {
                    file_path: norm_target.clone(),
                    content: format!("{}\n", helper_fn.trim()),
                    is_new: true,
                });
            }
        },
        ExtractTargetKind::NewModule
        | ExtractTargetKind::ExistingModule
        | ExtractTargetKind::Auto => {
            let target_file_path = if norm_target.ends_with(&format!(".{}", norm_ext)) {
                norm_target.clone()
            } else {
                format!("{}.{}", norm_target, norm_ext)
            };

            let content = match norm_ext.as_str() {
                "rs" => format!("#![forbid(unsafe_code)]\n\n{}\n", helper_fn.trim()),
                "ts" | "tsx" | "js" | "jsx" => format!(
                    "/**\n * Extracted shared utilities generated by CDDM.\n */\n\n{}\n",
                    helper_fn.trim()
                ),
                "py" => format!(
                    "\"\"\"Extracted shared utilities generated by CDDM.\"\"\"\n\n{}\n",
                    helper_fn.trim()
                ),
                "go" => format!("package common\n\n{}\n", helper_fn.trim()),
                "java" => {
                    let indented = wrap_indented_body(&helper_fn);
                    format!(
                        "/**\n * Extracted shared utilities generated by CDDM.\n */\npublic final \
                         class {}Utils {{\n    private {}Utils() {{}}\n\n{}\n}}\n",
                        pascal_target, pascal_target, indented
                    )
                }
                "cs" => {
                    let indented = wrap_indented_body(&helper_fn);
                    format!(
                        "namespace Common;\n\npublic static class {}Utils\n{{\n{}\n}}\n",
                        pascal_target, indented
                    )
                }
                _ => format!("{}\n", helper_fn.trim()),
            };

            files.push(ExtractedFile {
                file_path: target_file_path,
                content,
                is_new: target_kind != ExtractTargetKind::ExistingModule,
            });
        }
    }

    (helper_sig, files)
}

fn derive_target_name(path: &str) -> String {
    let p = Path::new(path);
    let stem = p
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("shared_utils");

    if stem.is_empty() || stem == "." || stem == "src" {
        "shared_utils".to_string()
    } else {
        stem.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_python_target_files() {
        let params = vec![InferredParameter {
            name: "x".to_string(),
            inferred_type: "int".to_string(),
            original_values: vec!["10".to_string()],
        }];
        let body = vec!["print(x)".to_string()];

        let (sig, files) = generate_extracted_target_files(
            "packages/data_helpers",
            ExtractTargetKind::NewCrate,
            "process",
            &params,
            &body,
            "py",
        );

        assert_eq!(sig, "def process(x: int) -> None:");
        assert_eq!(files.len(), 2);
        assert_eq!(files[0].file_path, "packages/data_helpers/pyproject.toml");
        assert_eq!(files[1].file_path, "packages/data_helpers/__init__.py");
        assert!(files[1].content.contains("def process(x: int) -> None:"));
    }

    #[test]
    fn test_generate_java_and_csharp_target_files() {
        let params = vec![InferredParameter {
            name: "msg".to_string(),
            inferred_type: "String".to_string(),
            original_values: vec!["\"test\"".to_string()],
        }];
        let body = vec!["System.out.println(msg);".to_string()];

        let (sig_j, files_j) = generate_extracted_target_files(
            "packages/core-utils",
            ExtractTargetKind::NewCrate,
            "logMessage",
            &params,
            &body,
            "java",
        );
        assert_eq!(sig_j, "public static void logMessage(String msg)");
        assert_eq!(files_j.len(), 2);

        let (sig_c, files_c) = generate_extracted_target_files(
            "packages/math_helpers",
            ExtractTargetKind::NewCrate,
            "compute",
            &params,
            &body,
            "cs",
        );
        assert_eq!(sig_c, "public static void Compute(String msg)");
        assert_eq!(files_c.len(), 2);
    }
}
