#![forbid(unsafe_code)]

use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;
use std::path::Path;

/// Generates files for the extracted crate or module based on target kind and language.
pub fn generate_extracted_target_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    inferred_params: &[InferredParameter],
    common_body_lines: &[String],
    ext: &str,
) -> (String, Vec<ExtractedFile>) {
    let norm_ext = ext.to_lowercase();
    let norm_target = target_path.replace('\\', "/");
    let target_name = derive_target_name(&norm_target);

    let helper_sig = crate::ast::type_infer::format_function_signature(
        &norm_ext,
        function_name,
        inferred_params,
    );

    let helper_fn = crate::ast::rewriter::synthesize_helper_function_block(
        &norm_ext,
        function_name,
        inferred_params,
        common_body_lines,
        "",
    );

    let mut files = Vec::new();

    match target_kind {
        ExtractTargetKind::NewCrate => {
            match norm_ext.as_str() {
                "rs" => {
                    let crate_ident = target_name.replace('-', "_");
                    let cargo_toml = format!(
                        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \
                         \"2021\"\ndescription = \"Extracted shared utility crate generated by \
                         CDDM\"\n\n[dependencies]\n",
                        crate_ident
                    );
                    files.push(ExtractedFile {
                        file_path: format!("{}/Cargo.toml", norm_target.trim_end_matches('/')),
                        content: cargo_toml,
                        is_new: true,
                    });

                    let lib_rs = format!(
                        "#![forbid(unsafe_code)]\n\n/// Extracted shared helper generated by \
                         CDDM.\n{}\n",
                        helper_fn.trim()
                    );
                    files.push(ExtractedFile {
                        file_path: format!("{}/src/lib.rs", norm_target.trim_end_matches('/')),
                        content: lib_rs,
                        is_new: true,
                    });
                }
                "ts" | "tsx" | "js" | "jsx" => {
                    let pkg_json = format!(
                        "{{\n  \"name\": \"{}\",\n  \"version\": \"0.1.0\",\n  \"description\": \
                         \"Extracted shared package generated by CDDM\",\n  \"main\": \
                         \"./src/index.ts\",\n  \"types\": \"./src/index.ts\"\n}}\n",
                        target_name
                    );
                    files.push(ExtractedFile {
                        file_path: format!("{}/package.json", norm_target.trim_end_matches('/')),
                        content: pkg_json,
                        is_new: true,
                    });

                    let index_ts = format!(
                        "/**\n * Extracted shared utilities generated by CDDM.\n */\n\n{}\n",
                        helper_fn.trim()
                    );
                    files.push(ExtractedFile {
                        file_path: format!("{}/src/index.ts", norm_target.trim_end_matches('/')),
                        content: index_ts,
                        is_new: true,
                    });
                }
                "py" => {
                    let init_py = format!(
                        "\"\"\"Extracted shared package generated by CDDM.\"\"\"\n\n{}\n",
                        helper_fn.trim()
                    );
                    files.push(ExtractedFile {
                        file_path: format!("{}/__init__.py", norm_target.trim_end_matches('/')),
                        content: init_py,
                        is_new: true,
                    });
                }
                "go" => {
                    let go_file = format!(
                        "package {}\n\n// Extracted shared utility generated by CDDM.\n{}\n",
                        target_name.replace('-', "_"),
                        helper_fn.trim()
                    );
                    files.push(ExtractedFile {
                        file_path: format!(
                            "{}/{}.go",
                            norm_target.trim_end_matches('/'),
                            function_name.to_lowercase()
                        ),
                        content: go_file,
                        is_new: true,
                    });
                }
                _ => {
                    // Generic new module file
                    files.push(ExtractedFile {
                        file_path: norm_target.clone(),
                        content: format!("{}\n", helper_fn.trim()),
                        is_new: true,
                    });
                }
            }
        }
        ExtractTargetKind::NewModule
        | ExtractTargetKind::ExistingModule
        | ExtractTargetKind::Auto => {
            let target_file_path = if norm_target.ends_with(&format!(".{}", norm_ext)) {
                norm_target.clone()
            } else {
                format!("{}.{}", norm_target, norm_ext)
            };

            let header = match norm_ext.as_str() {
                "rs" => "#![forbid(unsafe_code)]\n\n",
                "ts" | "tsx" | "js" | "jsx" => {
                    "/**\n * Extracted shared utilities generated by CDDM.\n */\n\n"
                }
                "py" => "\"\"\"Extracted shared utilities generated by CDDM.\"\"\"\n\n",
                "go" => "package common\n\n",
                _ => "",
            };

            let content = format!("{}{}\n", header, helper_fn.trim());
            files.push(ExtractedFile {
                file_path: target_file_path,
                content,
                is_new: target_kind != ExtractTargetKind::ExistingModule,
            });
        }
    }

    (helper_sig, files)
}

fn derive_target_name(path: &str) -> String {
    let p = Path::new(path);
    let stem = p
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("shared_utils");

    if stem.is_empty() || stem == "." || stem == "src" {
        "shared_utils".to_string()
    } else {
        stem.to_string()
    }
}
