#![forbid(unsafe_code)]

use super::generator::derive_target_name;
use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;
use std::path::Path;

/// Generates sample argument literals for test invocation based on inferred parameter metadata.
pub fn generate_sample_arguments(params: &[InferredParameter]) -> Vec<String> {
    params
        .iter()
        .map(|p| {
            if let Some(first_val) = p.original_values.first().filter(|v| !v.trim().is_empty()) {
                return first_val.clone();
            }
            match p.inferred_type.as_str() {
                "i32" | "i64" | "usize" | "int" | "number" | "Integer" | "Long" => "42".to_string(),
                "f32" | "f64" | "float" | "Double" => "3.14".to_string(),
                "bool" | "boolean" | "Boolean" => "true".to_string(),
                "&str" | "String" | "string" | "str" => "\"sample_input\"".to_string(),
                _ => "42".to_string(),
            }
        })
        .collect()
}

/// Generates idiomatic unit test files for the newly extracted helper function.
pub fn generate_unit_test_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    params: &[InferredParameter],
    language: &str,
) -> Vec<ExtractedFile> {
    let mut test_files = Vec::new();
    let norm_target = target_path.replace('\\', "/");
    let norm_ext = language.to_lowercase();
    let target_name = derive_target_name(&norm_target);
    let pascal_target = crate::ast::type_infer::to_pascal_case(&target_name);
    let pascal_fn = crate::ast::type_infer::to_pascal_case(function_name);
    let snake_fn = crate::ast::type_infer::to_snake_case(function_name);
    let sample_args = generate_sample_arguments(params);
    let args_joined = sample_args.join(", ");

    match norm_ext.as_str() {
        "rs" => {
            let (file_path, content) = if target_kind == ExtractTargetKind::NewCrate {
                let p = format!(
                    "{}/tests/{}_test.rs",
                    norm_target.trim_end_matches('/'),
                    snake_fn
                );
                let c = format!(
                    "//! Automated unit tests for `{}` generated by CDDM.\n\n#[test]\nfn \
                     test_{}_execution() {{\n    {}({});\n}}\n",
                    function_name, snake_fn, function_name, args_joined
                );
                (p, c)
            } else {
                let p = if norm_target.ends_with(".rs") {
                    norm_target.replace(".rs", "_test.rs")
                } else {
                    format!("{}_test.rs", norm_target)
                };
                let c = format!(
                    "#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn \
                     test_{}() {{\n        {}({});\n    }}\n}}\n",
                    snake_fn, function_name, args_joined
                );
                (p, c)
            };
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "ts" | "tsx" | "js" | "jsx" => {
            let (file_path, import_stmt) = if target_kind == ExtractTargetKind::NewCrate {
                let p = format!(
                    "{}/src/{}.test.ts",
                    norm_target.trim_end_matches('/'),
                    snake_fn
                );
                let i = format!("import {{ {} }} from \"./index\";", function_name);
                (p, i)
            } else {
                let base = if norm_target.ends_with(&format!(".{}", norm_ext)) {
                    norm_target
                        .trim_end_matches(&format!(".{}", norm_ext))
                        .to_string()
                } else {
                    norm_target.clone()
                };
                let p = format!("{}.test.ts", base);
                let stem = Path::new(&base)
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("module");
                let i = format!("import {{ {} }} from \"./{}\";", function_name, stem);
                (p, i)
            };

            let content = format!(
                "import {{ describe, expect, it }} from \"vitest\";\n{}\n\ndescribe(\"{}\", () => \
                 {{\n  it(\"should execute successfully without throwing\", () => {{\n    \
                 expect(() => {}({})).not.toThrow();\n  }});\n}};\n",
                import_stmt, function_name, function_name, args_joined
            );
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "py" => {
            let (file_path, import_path) = if target_kind == ExtractTargetKind::NewCrate {
                let p = format!(
                    "{}/tests/test_{}.py",
                    norm_target.trim_end_matches('/'),
                    snake_fn
                );
                let i = format!("from {} import {}", target_name, function_name);
                (p, i)
            } else {
                let base = if norm_target.ends_with(".py") {
                    norm_target.trim_end_matches(".py").to_string()
                } else {
                    norm_target.clone()
                };
                let p = format!("{}_test.py", base);
                let stem = Path::new(&base)
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("module");
                let i = format!("from {} import {}", stem, function_name);
                (p, i)
            };

            let content = format!(
                "\"\"\"Automated unit tests for {} generated by CDDM.\"\"\"\n\nimport \
                 pytest\n{}\n\n\ndef test_{}_execution():\n    \"\"\"Verify {} executes without \
                 unhandled exceptions.\"\"\"\n    {}({})\n",
                function_name, import_path, snake_fn, function_name, function_name, args_joined
            );
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "go" => {
            let pkg_name = target_name.replace('-', "_");
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!("{}/{}_test.go", norm_target.trim_end_matches('/'), snake_fn)
            } else {
                let base = if norm_target.ends_with(".go") {
                    norm_target.trim_end_matches(".go").to_string()
                } else {
                    norm_target.clone()
                };
                format!("{}_test.go", base)
            };

            let content = format!(
                "package {}\n\nimport \"testing\"\n\nfunc Test{}(t *testing.T) {{\n\t// Verify \
                 execution with sample inputs\n\t{}({})\n}}\n",
                pkg_name, pascal_fn, pascal_fn, args_joined
            );
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "java" => {
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "{}/src/test/java/com/cddm/shared/{}UtilsTest.java",
                    norm_target.trim_end_matches('/'),
                    pascal_target
                )
            } else {
                format!("{}/{}UtilsTest.java", norm_target, pascal_target)
            };

            let content = format!(
                "package com.cddm.shared;\n\nimport org.junit.jupiter.api.Test;\nimport static \
                 org.junit.jupiter.api.Assertions.*;\n\n/**\n * Automated unit test generated by \
                 CDDM.\n */\npublic class {}UtilsTest {{\n    @Test\n    public void test{}() \
                 {{\n        assertDoesNotThrow(() -> {{\n            {}Utils.{}({});\n        \
                 }});\n    }}\n}}\n",
                pascal_target, pascal_fn, pascal_target, function_name, args_joined
            );
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        "cs" => {
            let file_path = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "{}/tests/{}UtilsTests.cs",
                    norm_target.trim_end_matches('/'),
                    pascal_target
                )
            } else {
                format!("{}/{}UtilsTests.cs", norm_target, pascal_target)
            };

            let content = format!(
                "using Xunit;\nusing {};\n\nnamespace {}.Tests\n{{\n    public class \
                 {}UtilsTests\n    {{\n        [Fact]\n        public void Test{}()\n        \
                 {{\n            {}Utils.{}({});\n        }}\n    }}\n}}\n",
                pascal_target,
                pascal_target,
                pascal_target,
                pascal_fn,
                pascal_target,
                pascal_fn,
                args_joined
            );
            test_files.push(ExtractedFile {
                file_path,
                content,
                is_new: true,
            });
        }
        _ => {
            let p = format!("{}_test.{}", norm_target, norm_ext);
            let c = format!(
                "// Automated test generated by CDDM for {}\n{}({});\n",
                function_name, function_name, args_joined
            );
            test_files.push(ExtractedFile {
                file_path: p,
                content: c,
                is_new: true,
            });
        }
    }

    test_files
}

#[cfg(test)]
mod tests {
    use super::*;

    fn check_generated_test(
        path: &str,
        kind: ExtractTargetKind,
        func: &str,
        param_name: &str,
        param_type: &str,
        param_val: &str,
        lang: &str,
    ) -> ExtractedFile {
        let params = vec![InferredParameter {
            name: param_name.to_string(),
            inferred_type: param_type.to_string(),
            original_values: vec![param_val.to_string()],
        }];
        let mut tests = generate_unit_test_files(path, kind, func, &params, lang);
        assert_eq!(tests.len(), 1);
        tests.remove(0)
    }

    #[test]
    fn test_generate_rust_unit_tests() {
        let t = check_generated_test(
            "crates/math_utils",
            ExtractTargetKind::NewCrate,
            "compute_double",
            "val",
            "i32",
            "100",
            "rs",
        );
        assert_eq!(
            t.file_path,
            "crates/math_utils/tests/compute_double_test.rs"
        );
        assert!(t.content.contains("fn test_compute_double_execution()"));
        assert!(t.content.contains("compute_double(100);"));
    }

    #[test]
    fn test_generate_typescript_unit_tests() {
        let t = check_generated_test(
            "packages/list_helpers",
            ExtractTargetKind::NewCrate,
            "processItems",
            "items",
            "string[]",
            "[\"a\", \"b\"]",
            "ts",
        );
        assert_eq!(
            t.file_path,
            "packages/list_helpers/src/process_items.test.ts"
        );
        assert!(
            t.content
                .contains("import { describe, expect, it } from \"vitest\";")
        );
        assert!(
            t.content
                .contains("import { processItems } from \"./index\";")
        );
    }

    #[test]
    fn test_generate_python_unit_tests() {
        let t = check_generated_test(
            "services/common_math",
            ExtractTargetKind::NewCrate,
            "calculate_total",
            "multiplier",
            "int",
            "5",
            "py",
        );
        assert_eq!(
            t.file_path,
            "services/common_math/tests/test_calculate_total.py"
        );
        assert!(t.content.contains("import pytest"));
        assert!(t.content.contains("def test_calculate_total_execution():"));
    }
}
