#![forbid(unsafe_code)]

use super::generator::AuxiliaryGenContext;
use super::types::{ExtractTargetKind, ExtractedFile};
use crate::types::InferredParameter;

/// Generates sample argument literals for test invocation based on inferred parameter metadata.
pub fn generate_sample_arguments(params: &[InferredParameter]) -> Vec<String> {
    params
        .iter()
        .map(|p| {
            if let Some(first_val) = p.original_values.first().filter(|v| !v.trim().is_empty()) {
                return first_val.clone();
            }
            match p.inferred_type.as_str() {
                "i32" | "i64" | "usize" | "int" | "number" | "Integer" | "Long" => "42".to_string(),
                "f32" | "f64" | "float" | "Double" => "3.14".to_string(),
                "bool" | "boolean" | "Boolean" => "true".to_string(),
                "&str" | "String" | "string" | "str" => "\"sample_input\"".to_string(),
                _ => "42".to_string(),
            }
        })
        .collect()
}

/// Generates idiomatic unit test files for the newly extracted helper function.
pub fn generate_unit_test_files(
    target_path: &str,
    target_kind: ExtractTargetKind,
    function_name: &str,
    params: &[InferredParameter],
    language: &str,
) -> Vec<ExtractedFile> {
    let ctx = AuxiliaryGenContext::new(target_path, function_name, params, language);
    let mut test_files = Vec::new();

    match ctx.norm_ext.as_str() {
        "rs" => {
            let file_path = ctx.resolve_rs_path(target_kind, "tests", "test");
            let content = if target_kind == ExtractTargetKind::NewCrate {
                format!(
                    "//! Automated unit tests for `{}` generated by CDDM.\n\n#[test]\nfn \
                     test_{}_execution() {{\n    {}({});\n}}\n",
                    function_name, ctx.snake_fn, function_name, ctx.args_joined
                )
            } else {
                format!(
                    "#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn \
                     test_{}() {{\n        {}({});\n    }}\n}}\n",
                    ctx.snake_fn, function_name, ctx.args_joined
                )
            };
            test_files.push(ExtractedFile::new(file_path, content));
        }
        "ts" | "tsx" | "js" | "jsx" => {
            let (file_path, import_stmt) = super::generator::resolve_auxiliary_file_path(
                &ctx.norm_target,
                &ctx.snake_fn,
                function_name,
                "ts",
                target_kind,
                "test",
            );

            let content = format!(
                "import {{ describe, expect, it }} from \"vitest\";\n{}\n\ndescribe(\"{}\", () => \
                 {{\n  it(\"should execute successfully without throwing\", () => {{\n    \
                 expect(() => {}({})).not.toThrow();\n  }});\n}};\n",
                import_stmt, function_name, function_name, ctx.args_joined
            );
            test_files.push(ExtractedFile::new(file_path, content));
        }
        "py" => {
            let (file_path, import_path) = super::generator::resolve_auxiliary_file_path(
                &ctx.norm_target,
                &ctx.snake_fn,
                function_name,
                "py",
                target_kind,
                "test",
            );

            let content = format!(
                "\"\"\"Automated unit tests for {} generated by CDDM.\"\"\"\n\nimport \
                 pytest\n{}\n\n\ndef test_{}_execution():\n    \"\"\"Verify {} executes without \
                 unhandled exceptions.\"\"\"\n    {}({})\n",
                function_name,
                import_path,
                ctx.snake_fn,
                function_name,
                function_name,
                ctx.args_joined
            );
            test_files.push(ExtractedFile::new(file_path, content));
        }
        "go" => {
            let (file_path, pkg_name) = ctx.resolve_go_path(target_kind, "");
            let clean_file_path = file_path.replace("__test.go", "_test.go");
            let content = format!(
                "package {}\n\nimport \"testing\"\n\nfunc Test{}(t *testing.T) {{\n\t// Verify \
                 execution with sample inputs\n\t{}({})\n}}\n",
                pkg_name, ctx.pascal_fn, ctx.pascal_fn, ctx.args_joined
            );
            test_files.push(ExtractedFile::new(clean_file_path, content));
        }
        "java" => {
            let file_path = ctx.resolve_jvm_path(target_kind, "UtilsTest");
            let content = format!(
                "package com.cddm.shared;\n\nimport org.junit.jupiter.api.Test;\nimport static \
                 org.junit.jupiter.api.Assertions.*;\n\n/**\n * Automated unit test generated by \
                 CDDM.\n */\npublic class {}UtilsTest {{\n    @Test\n    public void test{}() \
                 {{\n        assertDoesNotThrow(() -> {{\n            {}Utils.{}({});\n        \
                 }});\n    }}\n}}\n",
                ctx.pascal_target, ctx.pascal_fn, ctx.pascal_target, function_name, ctx.args_joined
            );
            test_files.push(ExtractedFile::new(file_path, content));
        }
        "cs" => {
            let file_path = ctx.resolve_dotnet_path(target_kind, "Tests");
            let content = format!(
                "using Xunit;\nusing {};\n\nnamespace {}.Tests\n{{\n    public class \
                     {}UtilsTests\n    {{\n        [Fact]\n        public void \
                     Test{}Execution()\n        {{\n            {}Utils.{}({});\n        }}\n    \
                     }}\n}}\n",
                ctx.pascal_target,
                ctx.pascal_target,
                ctx.pascal_target,
                ctx.pascal_fn,
                ctx.pascal_target,
                function_name,
                ctx.args_joined
            );
            test_files.push(ExtractedFile::new(file_path, content));
        }
        _ => {
            let p = format!("{}_test.{}", ctx.norm_target, ctx.norm_ext);
            let c = format!(
                "// Automated unit tests generated by CDDM for {}\n{}({});\n",
                function_name, function_name, ctx.args_joined
            );
            test_files.push(ExtractedFile::new(p, c));
        }
    }

    test_files
}
