use std::path::Path;

/// Defines syntax properties for a programming language.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LanguageGrammar {
    /// Name of the language (e.g. "Rust")
    pub name: &'static str,
    /// File extensions associated with this language (without leading dot)
    pub extensions: &'static [&'static str],
    /// Language keywords
    pub keywords: &'static [&'static str],
    /// Prefix for single-line comments
    pub line_comment: &'static str,
    /// Delimiters for multi-line block comments (start, end)
    pub block_comment: Option<(&'static str, &'static str)>,
}

const fn make_c_style_grammar(
    name: &'static str,
    extensions: &'static [&'static str],
    keywords: &'static [&'static str],
) -> LanguageGrammar {
    LanguageGrammar {
        name,
        extensions,
        keywords,
        line_comment: "//",
        block_comment: Some(("/*", "*/")),
    }
}

/// A static registry of supported languages.
pub const SUPPORTED_LANGUAGES: &[LanguageGrammar] = &[
    make_c_style_grammar(
        "Rust",
        &["rs"],
        &[
            "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
            "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
            "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
            "unsafe", "use", "where", "while", "async", "await", "dyn",
        ],
    ),
    make_c_style_grammar(
        "TypeScript",
        &["ts", "tsx"],
        &[
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "new",
            "null",
            "return",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "as",
            "implements",
            "interface",
            "let",
            "package",
            "private",
            "protected",
            "public",
            "static",
            "yield",
            "any",
            "boolean",
            "constructor",
            "declare",
            "get",
            "module",
            "require",
            "number",
            "set",
            "string",
            "symbol",
            "type",
            "from",
            "of",
        ],
    ),
    make_c_style_grammar(
        "JavaScript",
        &["js", "jsx", "cjs", "mjs"],
        &[
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "new",
            "return",
            "super",
            "switch",
            "this",
            "throw",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "yield",
            "let",
            "await",
            "async",
            "null",
            "true",
            "false",
        ],
    ),
    LanguageGrammar {
        name: "Python",
        extensions: &["py"],
        keywords: &[
            "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
            "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
            "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise",
            "return", "try", "while", "with", "yield",
        ],
        line_comment: "#",
        block_comment: None,
    },
    make_c_style_grammar(
        "Go",
        &["go"],
        &[
            "break",
            "default",
            "func",
            "interface",
            "select",
            "case",
            "defer",
            "go",
            "map",
            "struct",
            "chan",
            "else",
            "goto",
            "package",
            "switch",
            "const",
            "fallthrough",
            "if",
            "range",
            "type",
            "continue",
            "for",
            "import",
            "return",
            "var",
        ],
    ),
    make_c_style_grammar(
        "Java",
        &["java"],
        &[
            "abstract",
            "continue",
            "for",
            "new",
            "switch",
            "assert",
            "default",
            "goto",
            "package",
            "synchronized",
            "boolean",
            "do",
            "if",
            "private",
            "this",
            "break",
            "double",
            "implements",
            "protected",
            "throw",
            "byte",
            "else",
            "import",
            "public",
            "throws",
            "case",
            "enum",
            "instanceof",
            "return",
            "transient",
            "catch",
            "extends",
            "int",
            "short",
            "try",
            "char",
            "final",
            "interface",
            "static",
            "void",
            "class",
            "finally",
            "long",
            "strictfp",
            "volatile",
            "const",
            "float",
            "native",
            "super",
            "while",
            "null",
            "true",
            "false",
        ],
    ),
    make_c_style_grammar(
        "C",
        &["c", "h"],
        &[
            "auto", "break", "case", "char", "const", "continue", "default", "do", "double",
            "else", "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long",
            "register", "restrict", "return", "short", "signed", "sizeof", "static", "struct",
            "switch", "typedef", "union", "unsigned", "void", "volatile", "while",
        ],
    ),
    make_c_style_grammar(
        "C++",
        &["cpp", "hpp", "cc", "hh", "cxx", "hxx"],
        &[
            "alignas",
            "alignof",
            "and",
            "and_eq",
            "asm",
            "auto",
            "bitand",
            "bitor",
            "bool",
            "break",
            "case",
            "catch",
            "char",
            "char16_t",
            "char32_t",
            "class",
            "compl",
            "concept",
            "const",
            "constexpr",
            "const_cast",
            "continue",
            "decltype",
            "default",
            "delete",
            "do",
            "double",
            "dynamic_cast",
            "else",
            "enum",
            "explicit",
            "export",
            "extern",
            "false",
            "float",
            "for",
            "friend",
            "goto",
            "if",
            "inline",
            "int",
            "long",
            "mutable",
            "namespace",
            "new",
            "noexcept",
            "not",
            "not_eq",
            "nullptr",
            "operator",
            "or",
            "or_eq",
            "private",
            "protected",
            "public",
            "register",
            "reinterpret_cast",
            "requires",
            "return",
            "short",
            "signed",
            "sizeof",
            "static",
            "static_assert",
            "static_cast",
            "struct",
            "switch",
            "template",
            "this",
            "thread_local",
            "throw",
            "true",
            "try",
            "typedef",
            "typeid",
            "typename",
            "union",
            "unsigned",
            "using",
            "virtual",
            "void",
            "volatile",
            "wchar_t",
            "while",
            "xor",
            "xor_eq",
        ],
    ),
    make_c_style_grammar(
        "C#",
        &["cs"],
        &[
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "virtual",
            "void",
            "volatile",
            "while",
        ],
    ),
    LanguageGrammar {
        name: "Ruby",
        extensions: &["rb", "rake", "gemspec"],
        keywords: &[
            "alias", "and", "begin", "break", "case", "class", "def", "defined?", "do", "else",
            "elsif", "end", "ensure", "false", "for", "if", "in", "module", "next", "nil", "not",
            "or", "redo", "rescue", "retry", "return", "self", "super", "then", "true", "undef",
            "unless", "until", "when", "while", "yield",
        ],
        line_comment: "#",
        block_comment: Some(("=begin", "=end")),
    },
    make_c_style_grammar(
        "PHP",
        &["php", "phtml"],
        &[
            "abstract",
            "and",
            "array",
            "as",
            "break",
            "callable",
            "case",
            "catch",
            "class",
            "clone",
            "const",
            "continue",
            "declare",
            "default",
            "die",
            "do",
            "echo",
            "else",
            "elseif",
            "empty",
            "enddeclare",
            "endfor",
            "endforeach",
            "endif",
            "endswitch",
            "endwhile",
            "eval",
            "exit",
            "extends",
            "final",
            "finally",
            "fn",
            "for",
            "foreach",
            "function",
            "global",
            "goto",
            "if",
            "implements",
            "include",
            "include_once",
            "instanceof",
            "insteadof",
            "interface",
            "isset",
            "list",
            "match",
            "namespace",
            "new",
            "or",
            "print",
            "private",
            "protected",
            "public",
            "readonly",
            "require",
            "require_once",
            "return",
            "static",
            "switch",
            "throw",
            "trait",
            "try",
            "unset",
            "use",
            "var",
            "while",
            "xor",
            "yield",
        ],
    ),
    make_c_style_grammar(
        "Kotlin",
        &["kt", "kts"],
        &[
            "as",
            "break",
            "class",
            "continue",
            "do",
            "else",
            "false",
            "for",
            "fun",
            "if",
            "in",
            "interface",
            "is",
            "null",
            "object",
            "package",
            "return",
            "super",
            "this",
            "throw",
            "true",
            "try",
            "typealias",
            "val",
            "var",
            "when",
            "while",
            "by",
            "catch",
            "constructor",
            "delegate",
            "dynamic",
            "field",
            "file",
            "finally",
            "get",
            "import",
            "init",
            "param",
            "property",
            "receiver",
            "set",
            "setparam",
            "where",
            "actual",
            "abstract",
            "annotation",
            "companion",
            "const",
            "crossinline",
            "data",
            "enum",
            "expect",
            "external",
            "final",
            "infix",
            "inline",
            "inner",
            "internal",
            "lateinit",
            "noinline",
            "open",
            "operator",
            "out",
            "override",
            "private",
            "protected",
            "public",
            "reified",
            "sealed",
            "suspend",
            "tailrec",
            "vararg",
        ],
    ),
    make_c_style_grammar(
        "Swift",
        &["swift"],
        &[
            "associatedtype",
            "class",
            "deinit",
            "enum",
            "extension",
            "fileprivate",
            "func",
            "import",
            "init",
            "inout",
            "internal",
            "let",
            "open",
            "operator",
            "private",
            "protocol",
            "public",
            "rethrows",
            "static",
            "struct",
            "subscript",
            "typealias",
            "var",
            "break",
            "case",
            "continue",
            "default",
            "defer",
            "do",
            "else",
            "fallthrough",
            "for",
            "guard",
            "if",
            "in",
            "repeat",
            "return",
            "switch",
            "where",
            "while",
            "as",
            "Any",
            "catch",
            "false",
            "is",
            "nil",
            "super",
            "self",
            "Self",
            "throw",
            "throws",
            "true",
            "try",
            "async",
            "await",
        ],
    ),
    LanguageGrammar {
        name: "SQL",
        extensions: &["sql"],
        keywords: &[
            "SELECT",
            "FROM",
            "WHERE",
            "INSERT",
            "INTO",
            "UPDATE",
            "DELETE",
            "CREATE",
            "DROP",
            "ALTER",
            "TABLE",
            "JOIN",
            "INNER",
            "LEFT",
            "RIGHT",
            "FULL",
            "OUTER",
            "ON",
            "GROUP",
            "BY",
            "ORDER",
            "HAVING",
            "LIMIT",
            "OFFSET",
            "UNION",
            "ALL",
            "DISTINCT",
            "AS",
            "AND",
            "OR",
            "NOT",
            "IN",
            "IS",
            "NULL",
            "LIKE",
            "BETWEEN",
            "EXISTS",
            "CASE",
            "WHEN",
            "THEN",
            "ELSE",
            "END",
            "INDEX",
            "VIEW",
            "TRIGGER",
            "PROCEDURE",
            "FUNCTION",
            "PRIMARY",
            "KEY",
            "FOREIGN",
            "REFERENCES",
            "DEFAULT",
            "CHECK",
            "UNIQUE",
            "CONSTRAINT",
            "CASCADE",
            "TRANSACTION",
            "COMMIT",
            "ROLLBACK",
            "select",
            "from",
            "where",
            "insert",
            "into",
            "update",
            "delete",
            "create",
            "drop",
            "alter",
            "table",
            "join",
            "on",
            "group",
            "by",
            "order",
            "having",
            "limit",
            "offset",
        ],
        line_comment: "--",
        block_comment: Some(("/*", "*/")),
    },
    LanguageGrammar {
        name: "Bash",
        extensions: &["sh", "bash"],
        keywords: &[
            "if", "then", "else", "elif", "fi", "case", "esac", "for", "while", "until", "do",
            "done", "in", "function", "select", "time", "return", "exit", "local", "export",
            "readonly", "set", "unset", "echo", "printf", "source",
        ],
        line_comment: "#",
        block_comment: None,
    },
    LanguageGrammar {
        name: "Lua",
        extensions: &["lua"],
        keywords: &[
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto",
            "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until",
            "while",
        ],
        line_comment: "--",
        block_comment: Some(("--[[", "]]")),
    },
    make_c_style_grammar(
        "CSS",
        &["css", "scss", "sass", "less"],
        &[
            "import",
            "media",
            "keyframes",
            "font-face",
            "page",
            "supports",
            "namespace",
        ],
    ),
    LanguageGrammar {
        name: "HTML",
        extensions: &["html", "htm"],
        keywords: &[],
        line_comment: "",
        block_comment: Some(("<!--", "-->")),
    },
    make_c_style_grammar("JSON", &["json"], &["true", "false", "null"]),
];

/// Gets the grammar definition for a given file path based on its extension.
///
/// Returns `None` if the extension is not recognized.
pub fn get_grammar_for_path(path: &Path) -> Option<&'static LanguageGrammar> {
    let ext = path.extension()?.to_str()?;
    let ext = ext.to_lowercase();
    SUPPORTED_LANGUAGES
        .iter()
        .find(|&grammar| grammar.extensions.contains(&ext.as_str()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn test_get_grammar_for_path() {
        let rs_path = Path::new("src/main.rs");
        let ts_path = Path::new("app/index.ts");
        let py_path = Path::new("script.py");
        let go_path = Path::new("server.go");
        let css_path = Path::new("style.css");
        let unknown_path = Path::new("file.xyz");
        let no_ext_path = Path::new("Makefile");

        assert_eq!(get_grammar_for_path(rs_path).unwrap().name, "Rust");
        assert_eq!(get_grammar_for_path(ts_path).unwrap().name, "TypeScript");
        assert_eq!(get_grammar_for_path(py_path).unwrap().name, "Python");
        assert_eq!(get_grammar_for_path(go_path).unwrap().name, "Go");
        assert_eq!(get_grammar_for_path(css_path).unwrap().name, "CSS");

        assert!(get_grammar_for_path(unknown_path).is_none());
        assert!(get_grammar_for_path(no_ext_path).is_none());
    }

    #[test]
    fn test_grammar_properties() {
        let rs_grammar = get_grammar_for_path(Path::new("test.rs")).unwrap();
        assert!(rs_grammar.keywords.contains(&"fn"));
        assert_eq!(rs_grammar.line_comment, "//");
        assert_eq!(rs_grammar.block_comment, Some(("/*", "*/")));

        let py_grammar = get_grammar_for_path(Path::new("test.py")).unwrap();
        assert!(py_grammar.keywords.contains(&"def"));
        assert_eq!(py_grammar.line_comment, "#");
        assert_eq!(py_grammar.block_comment, None);
    }

    #[test]
    fn test_all_supported_extensions() {
        for grammar in SUPPORTED_LANGUAGES {
            for ext in grammar.extensions {
                let filename = format!("test.{}", ext);
                let path = Path::new(&filename);
                let found = get_grammar_for_path(path).unwrap();
                assert_eq!(found.name, grammar.name);
            }
        }
    }

    #[test]
    fn test_supported_language_count() {
        assert!(SUPPORTED_LANGUAGES.len() >= 12);
    }
}
