#![forbid(unsafe_code)]

use super::types::{LanguageGrammar, make_c_style_grammar};

// cddm:ignore-start
pub const POLYGLOT_LANGUAGES: &[LanguageGrammar] = &[
    LanguageGrammar {
        name: "SQL",
        extensions: &["sql"],
        keywords: &[
            "SELECT",
            "FROM",
            "WHERE",
            "INSERT",
            "INTO",
            "UPDATE",
            "DELETE",
            "CREATE",
            "DROP",
            "ALTER",
            "TABLE",
            "JOIN",
            "INNER",
            "LEFT",
            "RIGHT",
            "FULL",
            "OUTER",
            "ON",
            "GROUP",
            "BY",
            "ORDER",
            "HAVING",
            "LIMIT",
            "OFFSET",
            "UNION",
            "ALL",
            "DISTINCT",
            "AS",
            "AND",
            "OR",
            "NOT",
            "IN",
            "IS",
            "NULL",
            "LIKE",
            "BETWEEN",
            "EXISTS",
            "CASE",
            "WHEN",
            "THEN",
            "ELSE",
            "END",
            "INDEX",
            "VIEW",
            "TRIGGER",
            "PROCEDURE",
            "FUNCTION",
            "PRIMARY",
            "KEY",
            "FOREIGN",
            "REFERENCES",
            "DEFAULT",
            "CHECK",
            "UNIQUE",
            "CONSTRAINT",
            "CASCADE",
            "TRANSACTION",
            "COMMIT",
            "ROLLBACK",
            "select",
            "from",
            "where",
            "insert",
            "into",
            "update",
            "delete",
            "create",
            "drop",
            "alter",
            "table",
            "join",
            "on",
            "group",
            "by",
            "order",
            "having",
            "limit",
            "offset",
        ],
        line_comment: "--",
        block_comment: Some(("/*", "*/")),
    },
    LanguageGrammar {
        name: "Bash",
        extensions: &["sh", "bash"],
        keywords: &[
            "if", "then", "else", "elif", "fi", "case", "esac", "for", "while", "until", "do",
            "done", "in", "function", "select", "time", "return", "exit", "local", "export",
            "readonly", "set", "unset", "echo", "printf", "source",
        ],
        line_comment: "#",
        block_comment: None,
    },
    LanguageGrammar {
        name: "Lua",
        extensions: &["lua"],
        keywords: &[
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto",
            "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until",
            "while",
        ],
        line_comment: "--",
        block_comment: Some(("--[[", "]]")),
    },
    make_c_style_grammar(
        "CSS",
        &["css", "scss", "sass", "less"],
        &[
            "import",
            "media",
            "keyframes",
            "font-face",
            "page",
            "supports",
            "namespace",
        ],
    ),
    LanguageGrammar {
        name: "HTML",
        extensions: &["html", "htm"],
        keywords: &[],
        line_comment: "",
        block_comment: Some(("<!--", "-->")),
    },
    make_c_style_grammar("JSON", &["json"], &["true", "false", "null"]),
    LanguageGrammar {
        name: "Zig",
        extensions: &["zig", "zon"],
        keywords: &[
            "fn",
            "const",
            "var",
            "pub",
            "test",
            "struct",
            "enum",
            "union",
            "error",
            "inline",
            "comptime",
            "extern",
            "export",
            "defer",
            "errdefer",
            "if",
            "else",
            "switch",
            "while",
            "for",
            "return",
            "break",
            "continue",
            "unreachable",
            "try",
            "catch",
            "async",
            "await",
            "suspend",
            "resume",
            "anytype",
            "void",
            "bool",
            "true",
            "false",
            "null",
            "undefined",
        ],
        line_comment: "//",
        block_comment: None,
    },
    make_c_style_grammar(
        "Scala",
        &["scala", "sc"],
        &[
            "def",
            "val",
            "var",
            "class",
            "trait",
            "object",
            "case",
            "extends",
            "with",
            "package",
            "import",
            "return",
            "if",
            "else",
            "match",
            "for",
            "while",
            "do",
            "try",
            "catch",
            "finally",
            "throw",
            "new",
            "this",
            "super",
            "null",
            "true",
            "false",
            "abstract",
            "final",
            "private",
            "protected",
            "override",
            "implicit",
            "lazy",
            "sealed",
            "type",
            "yield",
            "given",
            "using",
            "enum",
        ],
    ),
    LanguageGrammar {
        name: "Elixir",
        extensions: &["ex", "exs"],
        keywords: &[
            "def",
            "defp",
            "defmodule",
            "defmacro",
            "defstruct",
            "defprotocol",
            "defimpl",
            "do",
            "end",
            "if",
            "unless",
            "case",
            "cond",
            "with",
            "for",
            "receive",
            "try",
            "catch",
            "rescue",
            "after",
            "raise",
            "throw",
            "import",
            "require",
            "alias",
            "use",
            "fn",
            "nil",
            "true",
            "false",
            "when",
            "and",
            "or",
            "not",
            "in",
        ],
        line_comment: "#",
        block_comment: None,
    },
    LanguageGrammar {
        name: "Dockerfile",
        extensions: &["dockerfile", "containerfile"],
        keywords: &[
            "FROM",
            "RUN",
            "CMD",
            "LABEL",
            "EXPOSE",
            "ENV",
            "ADD",
            "COPY",
            "ENTRYPOINT",
            "VOLUME",
            "USER",
            "WORKDIR",
            "ARG",
            "ONBUILD",
            "STOPSIGNAL",
            "HEALTHCHECK",
            "SHELL",
            "from",
            "run",
            "cmd",
            "copy",
            "add",
            "env",
            "workdir",
            "expose",
            "entrypoint",
        ],
        line_comment: "#",
        block_comment: None,
    },
];
// cddm:ignore-end
