import { describe, expect, test } from "bun:test";
import {
  CLI_COMMANDS_CATALOG,
  TUI_TABS_CATALOG,
  generateCliMarkdownTable,
  generateTuiMarkdownTable,
  replaceAutogeneratedSection,
} from "./interface-docs-generator";
import {
  MCP_RESOURCES_CATALOG,
  MCP_TOOLS_CATALOG,
  WEBUI_MODALS_CATALOG,
  generateMcpResourcesMarkdownTable,
  generateMcpToolsMarkdownTable,
  generateWebUiModalsMarkdownTable,
} from "./interface-docs-mcp-webui";

describe("Interface Documentation Generator", () => {
  test("CLI commands catalog contains all 22 subcommands", () => {
    expect(CLI_COMMANDS_CATALOG.length).toBe(22);
    const names = CLI_COMMANDS_CATALOG.map((c) => c.name);
    expect(names).toContain("scan");
    expect(names).toContain("diff");
    expect(names).toContain("semantic");
    expect(names).toContain("refactor");
    expect(names).toContain("extract");
    expect(names).toContain("heal");
    expect(names).toContain("dead-code");
    expect(names).toContain("monorepo");
    expect(names).toContain("overlap");
    expect(names).toContain("hub");
    expect(names).toContain("coverage");
    expect(names).toContain("cache");
    expect(names).toContain("rules");
    expect(names).toContain("tui");
  });

  test("TUI tabs catalog contains all 12 tabs", () => {
    expect(TUI_TABS_CATALOG.length).toBe(12);
    expect(TUI_TABS_CATALOG[0]?.title).toBe("Overview");
    expect(TUI_TABS_CATALOG[11]?.title).toBe("Dead Code");
  });

  test("MCP catalog contains 30 tools and 14 resources", () => {
    expect(MCP_TOOLS_CATALOG.length).toBe(30);
    expect(MCP_RESOURCES_CATALOG.length).toBe(14);
  });

  test("WebUI catalog contains all 19 modals", () => {
    expect(WEBUI_MODALS_CATALOG.length).toBe(19);
  });

  test("Table generators produce valid Markdown tables", () => {
    const cliTable = generateCliMarkdownTable();
    expect(cliTable).toContain("| Command | Usage |");
    expect(cliTable).toContain("`cddm scan`");

    const tuiTable = generateTuiMarkdownTable();
    expect(tuiTable).toContain("| Tab # | Tab Title |");
    expect(tuiTable).toContain("Dead Code");

    const mcpToolsTable = generateMcpToolsMarkdownTable();
    expect(mcpToolsTable).toContain("| Tool Name | Category |");
    expect(mcpToolsTable).toContain("`scan_codebase`");
    expect(mcpToolsTable).toContain("`cddm_heal_refactor`");

    const mcpResTable = generateMcpResourcesMarkdownTable();
    expect(mcpResTable).toContain("| Resource URI | Name |");
    expect(mcpResTable).toContain("`cddm://workspace/health`");

    const webUiTable = generateWebUiModalsMarkdownTable();
    expect(webUiTable).toContain("| Modal / View | Trigger / Shortcut |");
    expect(webUiTable).toContain("`DiffScanResultsModal`");
  });

  test("replaceAutogeneratedSection updates target block", () => {
    const original = `# Doc Header\n\n<!-- AUTOGEN:CLI:START -->\nold content\n<!-- AUTOGEN:CLI:END -->\n\nFooter`;
    const updated = replaceAutogeneratedSection(original, "CLI", "| New Table |");
    expect(updated).toContain("| New Table |");
    expect(updated).not.toContain("old content");
    expect(updated).toContain("# Doc Header");
    expect(updated).toContain("Footer");
  });
});
