#!/usr/bin/env bun
/**
 * CDDM Master Interface Documentation Synchronizer.
 * Synchronizes:
 * 1. CLI Reference (docs/CLI.md)
 * 2. MCP Specification (docs/MCP.md)
 * 3. WebUI Manual (docs/WEBUI.md)
 * 4. TUI Manual (docs/TUI.md)
 * 5. Feature Matrix (docs/FEATURE_MATRIX.md)
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  generateCliMarkdownTable,
  generateTuiMarkdownTable,
  normalizeMarkdown,
  replaceAutogeneratedSection,
} from "./lib/interface-docs-generator";
import {
  generateMcpResourcesMarkdownTable,
  generateMcpToolsMarkdownTable,
  generateWebUiModalsMarkdownTable,
} from "./lib/interface-docs-mcp-webui";

export async function syncInterfaceDocs(
  workspaceRoot: string = process.cwd(),
  writeChanges: boolean = true,
): Promise<boolean> {
  let modifiedAny = false;

  // 1. Sync docs/CLI.md
  const cliPath = join(workspaceRoot, "docs/CLI.md");
  if (existsSync(cliPath)) {
    const original = readFileSync(cliPath, "utf-8");
    const updated = replaceAutogeneratedSection(original, "CLI", generateCliMarkdownTable());
    if (normalizeMarkdown(updated) !== normalizeMarkdown(original)) {
      if (writeChanges) {
        writeFileSync(cliPath, updated, "utf-8");
        console.log("\x1b[32m[OK] Synchronized docs/CLI.md\x1b[0m");
      }
      modifiedAny = true;
    }
  }

  // 2. Sync docs/MCP.md
  const mcpPath = join(workspaceRoot, "docs/MCP.md");
  if (existsSync(mcpPath)) {
    let content = readFileSync(mcpPath, "utf-8");
    const updatedTools = replaceAutogeneratedSection(
      content,
      "MCP_TOOLS",
      generateMcpToolsMarkdownTable(),
    );
    const updatedAll = replaceAutogeneratedSection(
      updatedTools,
      "MCP_RESOURCES",
      generateMcpResourcesMarkdownTable(),
    );
    if (normalizeMarkdown(updatedAll) !== normalizeMarkdown(content)) {
      if (writeChanges) {
        writeFileSync(mcpPath, updatedAll, "utf-8");
        console.log("\x1b[32m[OK] Synchronized docs/MCP.md\x1b[0m");
      }
      modifiedAny = true;
    }
  }

  // 3. Sync docs/WEBUI.md
  const webuiPath = join(workspaceRoot, "docs/WEBUI.md");
  if (existsSync(webuiPath)) {
    const original = readFileSync(webuiPath, "utf-8");
    const updated = replaceAutogeneratedSection(
      original,
      "WEBUI_MODALS",
      generateWebUiModalsMarkdownTable(),
    );
    if (normalizeMarkdown(updated) !== normalizeMarkdown(original)) {
      if (writeChanges) {
        writeFileSync(webuiPath, updated, "utf-8");
        console.log("\x1b[32m[OK] Synchronized docs/WEBUI.md\x1b[0m");
      }
      modifiedAny = true;
    }
  }

  // 4. Sync docs/TUI.md
  const tuiPath = join(workspaceRoot, "docs/TUI.md");
  if (existsSync(tuiPath)) {
    const original = readFileSync(tuiPath, "utf-8");
    const updated = replaceAutogeneratedSection(original, "TUI_TABS", generateTuiMarkdownTable());
    if (normalizeMarkdown(updated) !== normalizeMarkdown(original)) {
      if (writeChanges) {
        writeFileSync(tuiPath, updated, "utf-8");
        console.log("\x1b[32m[OK] Synchronized docs/TUI.md\x1b[0m");
      }
      modifiedAny = true;
    }
  }

  return modifiedAny;
}

async function main() {
  console.log("\x1b[36m--> Synchronizing all interface documentation & feature matrices...\x1b[0m");
  const hasChanges = await syncInterfaceDocs();
  if (hasChanges) {
    console.log("\x1b[32m[SUCCESS] All interface documents synchronized cleanly!\x1b[0m\n");
  } else {
    console.log("\x1b[32m[OK] All interface documentation is already 100% up to date.\x1b[0m\n");
  }
}

if (import.meta.main) {
  main().catch((err) => {
    console.error("Fatal doc synchronization error:", err);
    process.exit(1);
  });
}
