#![forbid(unsafe_code)]

use crate::types::SuppressionDirective;
use std::path::Path;

/// Determines if a file is a test file based on conventions.
pub fn is_test_path(path: &Path) -> bool {
    let p = path.to_string_lossy().replace('\\', "/").to_lowercase();
    let norm = p.trim_start_matches("./");
    norm.starts_with("tests/")
        || norm.starts_with("test/")
        || norm.contains("/tests/")
        || norm.contains("/test/")
        || norm.contains("/__tests__/")
        || norm.contains(".test.")
        || norm.contains(".spec.")
        || norm.contains("_test.")
        || norm.contains("_spec.")
        || norm.ends_with("test.rs")
}

/// Determines if a file is a mock or test fixture.
pub fn is_mock_path(path: &Path) -> bool {
    let p = path.to_string_lossy().replace('\\', "/").to_lowercase();
    let norm = p.trim_start_matches("./");
    norm.starts_with("mocks/")
        || norm.starts_with("mock/")
        || norm.starts_with("fixtures/")
        || norm.contains("/mocks/")
        || norm.contains("/mock/")
        || norm.contains("/__mocks__/")
        || norm.contains("/fixtures/")
        || norm.contains(".mock.")
        || norm.contains("_mock.")
}

/// Inspects the top lines of a file to detect common automated code generation headers.
pub fn is_generated_header(content: &str) -> bool {
    for line in content.lines().take(25) {
        let lower = line.to_lowercase();
        if lower.contains("@generated")
            || lower.contains("do not edit")
            || lower.contains("<auto-generated")
            || lower.contains("code generated by")
            || lower.contains("this file was generated")
            || lower.contains("this file is generated")
            || lower.contains("autogenerated by")
            || lower.contains("automatically generated")
        {
            return true;
        }
    }
    false
}

/// Parses inline suppression directives from source code.
pub fn parse_inline_directives(file_path: &str, content: &str) -> Vec<SuppressionDirective> {
    let mut directives = Vec::new();
    let mut current_block_start: Option<usize> = None;

    for (idx, line) in content.lines().enumerate() {
        let line_num = idx + 1;
        let trimmed = line.trim();

        if trimmed.contains("cddm:ignore-start")
            || trimmed.contains("cddm-ignore-start")
            || trimmed.contains("cddm:allow-start")
        {
            current_block_start = Some(line_num);
        } else if trimmed.contains("cddm:ignore-end")
            || trimmed.contains("cddm-ignore-end")
            || trimmed.contains("cddm:allow-end")
        {
            if let Some(start) = current_block_start {
                directives.push(SuppressionDirective {
                    file_path: file_path.to_string(),
                    start_line: start,
                    end_line: line_num,
                    directive_type: "ignore_block".to_string(),
                    reason: None,
                });
                current_block_start = None;
            }
        } else if trimmed.contains("cddm:ignore")
            || trimmed.contains("cddm-ignore")
            || trimmed.contains("#[cddm(allow)]")
            || trimmed.contains("#[cddm(allow_duplication)]")
            || trimmed.contains("@cddm_ignore")
        {
            directives.push(SuppressionDirective {
                file_path: file_path.to_string(),
                start_line: line_num,
                end_line: line_num + 1,
                directive_type: "ignore_line".to_string(),
                reason: None,
            });
        } else if trimmed.starts_with("#[cfg(test)]") {
            directives.push(SuppressionDirective {
                file_path: file_path.to_string(),
                start_line: line_num,
                end_line: content.lines().count(),
                directive_type: "ignore_tests".to_string(),
                reason: Some("#[cfg(test)]".to_string()),
            });
        }
    }

    if let Some(start) = current_block_start {
        directives.push(SuppressionDirective {
            file_path: file_path.to_string(),
            start_line: start,
            end_line: content.lines().count(),
            directive_type: "ignore_block".to_string(),
            reason: None,
        });
    }

    directives
}
