#![forbid(unsafe_code)]

pub mod directives;
pub mod engine;
pub mod parser;

pub use directives::{is_generated_header, is_mock_path, is_test_path, parse_inline_directives};
pub use engine::SuppressionEngine;
pub use parser::{
    format_rules_to_raw, generate_default_cddmignore, parse_cddmignore_content, parse_clone_types,
};

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::CloneType;
    use std::path::Path;
    use tempfile::tempdir;

    #[test]
    fn test_parse_cddmignore_rules() {
        let content = r#"
# General ignore
tests/**
src/fixtures/**

# Threshold override
[threshold] benchmarks/** min_tokens=150

# Clone type filter
[type-filter] legacy/** ignore=Exact,Renamed
"#;
        let rules = SuppressionEngine::parse_cddmignore_content(content);
        assert_eq!(rules.len(), 4);
        assert_eq!(rules[0].pattern, "tests/**");
        assert_eq!(rules[0].rule_type, "ignore");

        assert_eq!(rules[2].pattern, "benchmarks/**");
        assert_eq!(rules[2].rule_type, "threshold");
        assert_eq!(rules[2].min_tokens, Some(150));

        assert_eq!(rules[3].pattern, "legacy/**");
        assert_eq!(rules[3].rule_type, "type_filter");
        assert_eq!(
            rules[3].ignored_clone_types,
            vec![CloneType::Exact, CloneType::Renamed]
        );
    }

    #[test]
    fn test_is_path_ignored_glob() {
        let content = "tests/**\n*.generated.ts\n";
        let engine = SuppressionEngine::from_str(content, false, false, false).unwrap();

        assert!(engine.is_path_ignored(Path::new("tests/unit/test_app.rs"), None));
        assert!(engine.is_path_ignored(Path::new("src/models/user.generated.ts"), None));
        assert!(!engine.is_path_ignored(Path::new("src/models/user.ts"), None));
    }

    #[test]
    fn test_is_generated_header() {
        let generated_code = r#"// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  protoc-gen-go v1.28.0
package models
"#;
        assert!(SuppressionEngine::is_generated_header(generated_code));

        let normal_code = r#"// Copyright 2026 Grigor Tonikyan
package models

func Calculate() int { return 42 }
"#;
        assert!(!SuppressionEngine::is_generated_header(normal_code));
    }

    #[test]
    fn test_inline_suppression_directives() {
        let code = r#"
fn a() {
    // cddm:ignore
    let dup_code = 123;
}

// cddm:ignore-start
fn b() {
    let block_dup = 456;
}
// cddm:ignore-end

fn c() {
    let clean = 789;
}
"#;
        let directives = SuppressionEngine::parse_inline_directives("src/a.rs", code);
        assert_eq!(directives.len(), 2);

        let mut engine = SuppressionEngine::default_engine();
        engine.register_file_directives("src/a.rs", code);

        assert!(engine.is_span_suppressed("src/a.rs", 3, 4));
        assert!(engine.is_span_suppressed("src/a.rs", 8, 10));
        assert!(!engine.is_span_suppressed("src/a.rs", 14, 16));
    }

    #[test]
    fn test_threshold_and_type_filter_overrides() {
        let content = r#"
[threshold] benches/** min_tokens=200
[type-filter] legacy/** ignore=Exact
"#;
        let engine = SuppressionEngine::from_str(content, false, false, false).unwrap();

        assert_eq!(
            engine.get_effective_min_tokens(Path::new("benches/bench.rs"), 50),
            200
        );
        assert_eq!(
            engine.get_effective_min_tokens(Path::new("src/main.rs"), 50),
            50
        );

        assert!(engine.is_clone_type_ignored(Path::new("legacy/old.rs"), &CloneType::Exact));
        assert!(!engine.is_clone_type_ignored(Path::new("legacy/old.rs"), &CloneType::NearMiss));
    }

    #[test]
    fn test_from_file_lifecycle() {
        let dir = tempdir().unwrap();
        let file_path = dir.path().join(".cddmignore");
        let content = SuppressionEngine::generate_default_cddmignore();
        std::fs::write(&file_path, content).unwrap();

        let engine = SuppressionEngine::from_file(&file_path, true, true, true).unwrap();
        assert!(engine.is_path_ignored(Path::new("tests/app_test.rs"), None));
        assert!(engine.is_path_ignored(Path::new("src/fixtures/mock.json"), None));
    }
}
